<a href="https://colab.research.google.com/github/shubham-k01/SDS_Exps/blob/main/STATS_EXP6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Question 1: Out of 500 students, 410 students pass the exam. Test the hypothesis that more than 80% of students pass the exam. Level of significance = 5%**

In [ ]:
# Ho : P=0.8 ,Ha: P>0.8
from scipy.stats import norm
p_p = 0.8
sample_success=410
sample_size=500
alpha=0.05
from statsmodels.stats.proportion import proportions_ztest
stat,p_value=proportions_ztest(count=sample_success,nobs=sample_size,value=p_p,alternative="larger")
print("z_stat = ",stat,"p_value = ",p_value)
z_cri=norm.ppf(0.95)
print("z_cri = ",z_cri)

z_stat =  1.1640504929492914 p_value =  0.12220177493249235
z_cri =  1.6448536269514722


In [ ]:
import numpy as np
s_p=sample_success/sample_size
SE=np.sqrt(p_p*(1-p_p)/sample_size)
z=(s_p-p_p)/SE
print("z-stat= ",z)
z_cri=norm.ppf(0.95)
print("z-cri= ",z_cri)
p=norm.sf(z)
print("p-value= ",p)
if p>alpha:
  print("Test is not significant . Fail to reject null hypothesis.")
else:
  print("Test is significant . Reject null hypothesis.")


z-stat=  1.1180339887498898
z-cri=  1.6448536269514722
p-value=  0.1317762386414874
Test is not significant . Fail to reject null hypothesis.


**Question 2: A random sample of 35 individuals selected from a certain population showed that 6 of them are left-handed. Find 95% and 99% confidence limits for the proportions of left-handed person in the population.**

In [ ]:
import numpy as np
s_p=6/35
n=35
SE=np.sqrt(s_p*(1-s_p)/n)
z=norm.ppf(0.975)
L=s_p-z*SE
U=s_p+z*SE
CI=(L,U)
print("95% Confidence Interval = ",np.round(CI,4))
z=norm.ppf(0.995)
L=s_p-z*SE
U=s_p+z*SE
CI=(L,U)
print("99% Confidence Interval = ",np.round(CI,4))

95% Confidence Interval =  [0.0466 0.2963]
99% Confidence Interval =  [0.0073 0.3355]


**Question 3: The manufacturer of patent medicine claimed that it was 90℅ effective in relieving allergy for a period of 8 hours. In a sample of 200 people who had the allergy, the medicine provided relief for 160 people. Determine whether manufacturer's claim is legitimate.**



In [ ]:
from scipy.stats import norm
# Ho: P=0.9 ,Ha: P!=0.9
p_p=0.9
sample_success=160
sample_size=200
alpha=0.05
s_p=sample_success/sample_size
SE=np.sqrt(p_p*(1-p_p)/sample_size)
z=(s_p-p_p)/SE
print("z-stat= ",z)
z_cri=norm.ppf(0.025)
print("z-cri= ",z_cri)
p=2*norm.cdf(z)
print("p-value= ",p)
if p>alpha:
  print("Test is not significant . Fail to reject null hypothesis.")
else:
  print("Test is significant . Reject null hypothesis.")

z-stat=  -4.714045207910316
z-cri=  -1.9599639845400545
p-value=  2.4284674729758487e-06
Test is significant . Reject null hypothesis.


**Question 4: From one class of 500 students, 410 students passed. From other class of 400 students, 379 students passed. Test the hypothesis that both samples have same proportions. Level of significance = 0.025**



In [ ]:
#Ho: P1=P2 Ha: P!=P2
alpha=0.025
success=np.array([410,379])
sample=np.array([500,400])
stat,p_value=proportions_ztest(count=success,nobs=sample,alternative='two-sided')
print("z_stat: %0.3f ,p_value: %0.15f"%(stat,p_value))
if p_value>alpha:
  print("Test is not significant , fail to reject null hypothesis")
else:
  print("Test is significant , Reject null hypothesis")

z_stat: -5.780 ,p_value: 0.000000007459074
Test is significant , Reject null hypothesis


**Question 5: Two groups, A and B, each consists of 100 people who have a disease. A serum is given to group A but not group B; otherwise both the groups are treated identically. It's found that in group A and group B, 75 and 65 people respectively, recover from the disease. Test the hypothesis that serum helps to cure the disease using a level of significance (a) 0.01 (b) 0.1.**

In [ ]:
#Ho: P1=P2 Ha: P1>P2
alpha=0.01
success=np.array([75,65])
sample=np.array([100,100])
stat,p_value=proportions_ztest(count=success,nobs=sample,alternative='larger')
print("z_stat: %0.3f ,p_value: %0.15f"%(stat,p_value))
if p_value>alpha:
  print("Test is not significant at 0.01 level of significance .Fail to reject null hypothesis")
else:
  print("Test is significant at 0.01 level of significance .Reject null hypothesis")

z_stat: 1.543 ,p_value: 0.061411324050696
Test is not significant at 0.01 level of significance .Fail to reject null hypothesis


In [ ]:
#Ho: P1=P2 Ha: P1>P2
alpha=0.01
success=np.array([75,65])
sample=np.array([100,100])
stat,p_value=proportions_ztest(count=success,nobs=sample,alternative='larger')
print("z_stat: %0.3f ,p_value: %0.15f"%(stat,p_value))
if p_value>alpha:
  print("Test is not significant at 0.1 level of significance .Fail to reject null hypothesis")
else:
  print("Test is significant at 0.1 level of significance .Reject null hypothesis")

z_stat: 1.543 ,p_value: 0.061411324050696
Test is not significant at 0.1 level of significance .Fail to reject null hypothesis


**Question 6: Check the hypothesis that blood pressure before treatment has a mean value of 156 for the given dataset.**

In [ ]:
import pandas as pd
df=pd.read_csv("/content/blood_pressure.csv")
df.head()

patient   sex agegrp  bp_before  bp_after
0        1  Male  30-45        143       153
1        2  Male  30-45        163       170
2        3  Male  30-45        153       168
3        4  Male  30-45        153       142
4        5  Male  30-45        146       141

In [ ]:
df.describe()

patient   bp_before    bp_after
count  120.000000  120.000000  120.000000
mean    60.500000  156.450000  151.358333
std     34.785054   11.389845   14.177622
min      1.000000  138.000000  125.000000
25%     30.750000  147.000000  140.750000
50%     60.500000  154.500000  149.500000
75%     90.250000  164.000000  161.000000
max    120.000000  185.000000  185.000000

In [ ]:
#Ho: Populaton mean for BP =156 ,Ha: Population mean for BP !=156
alpha=0.05
from statsmodels.stats import weightstats as stests
z_stats, p_val= stests.ztest(df['bp_before'],x2=None,value=156,alternative='two-sided')
print("z_statistic = ",z_stats,"p value= ",p_val)
print("z_critical = ", norm.ppf(0.975))
if p_value>alpha:
  print("Test is not significant at 0.05 level of significance .Fail to reject null hypothesis")
else:
  print("Test is significant at 0.05 level of significance .Reject null hypothesis")


z_statistic =  0.432798073526164 p value=  0.6651614730255063
z_critical =  1.959963984540054
Test is not significant at 0.05 level of significance .Fail to reject null hypothesis


**Question 7: Can we say that the systolic blood pressure measured on arm has mean value of 125 mmHg from the given dataset?**

In [ ]:
  df=pd.read_csv('/content/systolic blood pressure.csv')
  df.head()

armsys  fingsys
0     140      154
1     110      112
2     138      156
3     124      152
4     142      142

In [ ]:
df.describe()

armsys     fingsys
count  200.000000  200.000000
mean   128.520000  132.815000
std     23.287575   25.648195
min     79.000000   60.000000
25%    111.500000  118.000000
50%    125.000000  130.000000
75%    140.000000  146.500000
max    220.000000  228.000000

In [ ]:
#Ho: Populaton mean for systolic BP =125 ,Ha: Population mean for systolic BP !=125
alpha=0.05
from statsmodels.stats import weightstats as stests
z_stats, p_val= stests.ztest(df['armsys'],x2=None,value=125,alternative='two-sided')
print("z_statistic = ",z_stats,"p value= ",p_val)
print("z_critical = ", norm.ppf(0.975))
if p_value>alpha:
  print("Test is not significant at 0.05 level of significance .Fail to reject null hypothesis")
else:
  print("Test is significant at 0.05 level of significance .Reject null hypothesis")


z_statistic =  2.1376342148925 p value=  0.032546442541153964
z_critical =  1.959963984540054
Test is not significant at 0.05 level of significance .Fail to reject null hypothesis


**Question 8: A sample of 50 pieces of certain type of string was tested. The mean breaking strength turned out to be 14.5 pounds. Test whether the sample is from a batch of string having mean breaking strength of 15.6 pounds and standard deviation of 2.2 pounds.**

In [ ]:
 #Ho: Pop mean=15.6 , Ha: Pop mean !=15.6
alpha=0.05
x_bar=14.5
mean=15.6
sigma=2.2
n=50
SE=sigma/np.sqrt(n)
z=(x_bar-mean)/SE
print("Z_stats = ",z)
print("Z_critical = ",norm.ppf(0.025))
p_val=2*norm.cdf(z)
print("p-value = ",p_val)
if p_val>alpha:
  print("Test is not significant at 0.05 level of significance .Fail to reject null hypothesis")
else:
  print("Test is significant at 0.05 level of significance .Reject null hypothesis")

Z_stats =  -3.5355339059327364
Z_critical =  -1.9599639845400545
p-value =  0.0004069520174449609
Test is significant at 0.05 level of significance .Reject null hypothesis


**Question 9: Check the hypothesis that mean value of systolic blood pressure measured on arm and finger are the same.**

In [ ]:
df=pd.read_csv('/content/systolic blood pressure.csv')
df.head()

armsys  fingsys
0     140      154
1     110      112
2     138      156
3     124      152
4     142      142

In [ ]:
 df.describe()

armsys     fingsys
count  200.000000  200.000000
mean   128.520000  132.815000
std     23.287575   25.648195
min     79.000000   60.000000
25%    111.500000  118.000000
50%    125.000000  130.000000
75%    140.000000  146.500000
max    220.000000  228.000000

In [ ]:
#Ho: Populaton mean 1= Population mean 2 ,Ha: Populaton mean 1 != Population mean 2
alpha=0.05
from statsmodels.stats import weightstats as stests
z_stats, p_val= stests.ztest(df['armsys'],x2=df['fingsys'],value=0,alternative='two-sided')
print("z_statistic = ",z_stats,"p value= ",p_val)
print("z_critical = ", norm.ppf(0.975))
if p_value>alpha:
  print("Test is not significant at 0.05 level of significance .Fail to reject null hypothesis")
else:
  print("Test is significant at 0.05 level of significance .Reject null hypothesis")


z_statistic =  -1.7533233440871472 p value=  0.07954652069053099
z_critical =  1.959963984540054
Test is not significant at 0.05 level of significance .Fail to reject null hypothesis


**Question 10: A common perception about COVID-19 is that warm climate is more resistant to the corona outbreak. Verify this using hypothesis testing.**

In [ ]:
corona=pd.read_csv('/content/Corona_Updated.csv')
corona.head()

Province/State              Country/Region  ... Temp_Cat  Humid_Cat
0          Hubei              Mainland China  ...        1          1
1            NaN                       Italy  ...        1          1
2            NaN  Iran (Islamic Republic of)  ...        0          0
3            NaN           Republic of Korea  ...        0          0
4            NaN                      France  ...        0          0

[5 rows x 12 columns]

In [ ]:
corona.describe()

Confirmed       Deaths  ...    Temp_Cat   Humid_Cat
count    206.000000   206.000000  ...  206.000000  206.000000
mean     575.640777    20.689320  ...    0.470874    0.470874
std     4822.697784   215.794845  ...    0.500367    0.500367
min        0.000000     0.000000  ...    0.000000    0.000000
25%        3.000000     0.000000  ...    0.000000    0.000000
50%       12.000000     0.000000  ...    0.000000    0.000000
75%       75.750000     1.000000  ...    1.000000    1.000000
max    67760.000000  3024.000000  ...    1.000000    1.000000

[8 rows x 9 columns]

In [ ]:
corona['Temp_Cat']=corona['Temprature'].apply(lambda x:0 if x<24 else 1)
corona_t=corona[['Confirmed','Temp_Cat']]
corona_t.head()
d1=corona_t[(corona_t['Temp_Cat']==1)]['Confirmed']
d2=corona_t[(corona_t['Temp_Cat']==0)]['Confirmed']
m1=d1.mean()
m2=d2.mean()
s1=d1.std()
s2=d2.std()
n1=d1.shape[0]
n2=d2.shape[0]
print("Mean confirmed cases for warm climate = ",m1 ,"Mean confirmed cases for not warm climate = ", m2)
print(s1,s2,n1,n2)

Mean confirmed cases for warm climate =  26.548387096774192 Mean confirmed cases for not warm climate =  672.9085714285715
45.93969867095882 5228.628797929274 31 175


* Ho: Mean value of confirmed cases with warm climate =Mean value of confirmed cases with not warm climate
* Ha: Mean value of confirmed cases with warm climate < Mean value of confirmed cases with not warm climate 

In [ ]:
SE =np.sqrt(s1**2/n1 + s2**2/n2)
z=(m1-m2)/SE
p_val=norm.cdf(z)
print("Z statistic =",z,"p-value= ",p_val) 
if (p_val<0.05):
  print("Test is significant at 0.05 LOS, Reject null hypothesis")
else:
  print("Test is not significant at 0.05 LOS . Fail to reject null hypothesis")


Z statistic = -1.6349753148440753 p-value=  0.05102711125709931
Test is not significant at 0.05 LOS . Fail to reject null hypothesis


In [ ]:
SE =np.sqrt(s1**2/n1 + s2**2/n2)
z=(m1-m2)/SE
p_val=norm.cdf(z)
print("Z statistic =",z,"p-value= ",p_val) 
if (p_val<0.1):
  print("Test is significant at 0.1 LOS, Reject null hypothesis")
else:
  print("Test is not significant at 0.1 LOS . Fail to reject null hypothesis")


Z statistic = -1.6349753148440753 p-value=  0.05102711125709931
Test is significant at 0.1 LOS, Reject null hypothesis


**Question 11: The mean consumption of food grains among 400 samples middle class consumers is 380 grams per day per person with a standard deviation of 120 grams. A similar sample survey of 600 working class consumers gave a mean of 410 grams with standard deviation of 80 grams. Are we justified in saying that the difference between the averages of the two classes is 40? Use 5℅ level of significance.**

In [ ]:
#Ho: |Mean 1- Mean 2|=40 , Ha: |Mean 1- Mean 2|!=40 
n1,n2,m1,m2,s1,s2=400,600,380,410,120,80
SE =np.sqrt(s1**2/n1 + s2**2/n2)
z=(abs(m1-m2)-40)/SE
p_val=2*norm.cdf(z)
print("Z statistic =",z,"p-value= ",p_val) 
if (p_val<0.05):
  print("Test is significant at 0.05 LOS, Reject null hypothesis")
else:
  print("Test is not significant at 0.05 LOS . Fail to reject null hypothesis")


Z statistic = -1.4638501094227998 p-value=  0.14323490752466972
Test is not significant at 0.05 LOS . Fail to reject null hypothesis


**Question 12: Two populations have same mean but the standard deviation of one is twice that of the other. Show that in samples, each of size 500, drawn under simple random conditions, the difference of the means will not exceed 0.3 σ, where σ is the smaller standard deviation.**

In [ ]:
# m1=m2 , s2 = 2 s1 ,n1=n2=500
#Z=(X1-X2)/sqrt((s1^2/n1) + (s2^2/n2))
#Z=(X1-X2)/sqrt((s^2/500) + (4s^2/n2))
#Z=(X1-X2)/(s/10)
#(X1-X2) < = 0.3s
#(X1-X2) /(s/10) < =0.3s/(s/10)
#(X1-X2) /(s/10) < =3
#z <=3
#Prob (Z=3) 
print(norm.cdf(3))
print("For standard normal variable z=3 , 99.86 % area lies under the curve so the difference of the means will not exceed 0.3 σ ")

0.9986501019683699
For standard normal variable z=3 , 99.86 % area lies under the curve so the difference of the means will not exceed 0.3 σ 
